const SHIPPING_SHEET_NAME = "Отгрузки";
const SHIPPING_DATA_RANGE = "B5:U";
const SHIPPING_DATA_FIRST_ROW = 5;
const SHIPPING_DATA_FIRST_COL = 3;
const SHIPPING_DATA_LAST_COL_OFFSET = 0;
const SHIPPING_DATA_PROFIT_COL = 19
const SHIPPING_DATA_PROFIT_LAST_COL = 22

const PURCHASING_SHEET_NAME = "Закупки";
const PURCHASING_DATA_RANGE = "B5:Q";
const PURCHASING_DATA_FIRST_ROW = 5;
const PURCHASING_DATA_FIRST_COL = 1;
const PURCHASING_DATA_LAST_COL_OFFSET = 0;

const PLACEMENTS_DATA_FIRST_ROW = 5
const PLACEMENTS_DATA_FIRST_COL = 1
const PLACEMENTS_DATA_LAST_COL = 9
const PLACEMENTS_DATA_LAST_COL_OFFSET = 0
const PLACEMENTS_DATA_SEBES_COL = 14

const HANDBOOK_SHEET_NAME = "Справочник";
const HANDBOOK_NUM_DAYS_CELL = "G5";
const HANDBOOK_FIFO_CELL = "M5";
const HANDBOOK_LIFO_CELL = "G7";

const REMAINS_DATA_FIRST_ROW = 5
const REMAINS_DATA_FIRST_COL = 2
const REMAINS_DATA_LAST_COL = 10

const UNPLACED_REMAINS_DATA_FIRST_ROW = 5
const UNPLACED_REMAINS_DATA_FIRST_COL = 2
const UNPLACED_REMAINS_DATA_EMPTY_FIRST_COL = 8
const UNPLACED_REMAINS_DATA_LAST_COL = 9

const REMAINS_TECH_DATA_FIRST_ROW = 3
const REMAINS_TECH_DATA_FIRST_COL = 1
const REMAINS_TECH_DATA_LAST_COL = 9

const EXCEL_REGISTRY_DATA_FIRST_ROW = 5
const EXCEL_REGISTRY_DATA_FIRST_COL = 1

const SEARCH_FILTER_ROW = 3
const SEARCH_FILTER_FIRST_COL = 1
const SEARCH_FILTER_LAST_COL = 5
const SEARCH_DATA_FIRST_ROW = 6
const SEARCH_DATA_FIRST_COL = 1

const CART_DATA_FIRST_ROW = 4
const CART_DATA_FIRST_COL = 1