const HANDBOOK_SHEET_NAME = "Справочник";
const HANDBOOK_NUM_DAYS_CELL = "G5";
const HANDBOOK_FIFO_CELL = "M5";
const HANDBOOK_LIFO_CELL = "G7";

const REMAINS_DATA_FIRST_ROW = 5
const REMAINS_DATA_FIRST_COL = 2
const REMAINS_DATA_LAST_COL = 10

const REMAINS_TECH_DATA_FIRST_ROW = 3
const REMAINS_TECH_DATA_FIRST_COL = 1
const REMAINS_TECH_DATA_LAST_COL = 9

const EXCEL_REGISTRY_DATA_FIRST_ROW = 5
const EXCEL_REGISTRY_DATA_FIRST_COL = 1

const SEARCH_FILTER_ROW = 3
const SEARCH_FILTER_FIRST_COL = 1
const SEARCH_FILTER_LAST_COL = 5
const SEARCH_DATA_FIRST_ROW = 6
const SEARCH_DATA_FIRST_COL = 1